#! /usr/bin/env bash
trap "kill 9" EXIT

export NODE_ENV=dev
export LIVE_PORT=35729

node -e '
  const livereload = require("livereload");
  const liveServer = livereload.createServer({
    hostname: "0.0.0.0",
    port: '$LIVE_PORT',
  });
  liveServer.watch(process.cwd());
' &

nodemon -w src -e ts,html \
  --exec "npm run tailwind && \
    rm -rf ./dist && mkdir -p dist && \
    cp ./src/worker.js ./dist/worker.js && \
    cp -r ./src/assets ./dist/assets && \
    ./scripts/build && \
    node dist/index.js --host 0.0.0.0 --allow-duplicate-nicknames"
